Repository HRIS-M/HRIS, pull requests merged in 2024-06, with the labels that each got.

#278 Fix: dependency injection error
  src/main/java/com/hris/HRIS/dto/MeetingRequest.java
  src/main/java/com/hris/HRIS/model/ApplyJobModel.java
Labels: bug, fixed

#282 Raini new
  src/main/java/com/hris/HRIS/controller/RecruiterController.java
  src/main/java/com/hris/HRIS/dto/HireRequest.java
  src/main/java/com/hris/HRIS/dto/MeetingRequest.java
  src/main/java/com/hris/HRIS/model/ApplyJobModel.java
  src/main/java/com/hris/HRIS/service/ApplyJobService.java
  src/main/java/com/hris/HRIS/service/EmailService.java
Labels: fixed

#287 [fix]: date picker
  client/src/app/components/Dashboards/dashboard-initial/dashboard-initial.component.ts
  client/src/app/shared/dialogs/event-add/event-add.component.html
  client/src/app/shared/dialogs/event-add/event-add.component.ts
Labels: fixed

#288 Update: event backend handlers
  client/src/app/services/event.service.ts
  client/src/app/shared/components/event-calendar/event-calendar.component.ts
  client/src/app/shared/dialogs/event-add/event-add.component.html
  client/src/app/shared/dialogs/event-add/event-add.component.ts
  src/main/java/com/hris/HRIS/controller/EventController.java
  src/main/java/com/hris/HRIS/model/EventModel.java
  src/main/java/com/hris/HRIS/service/EventService.java
Labels: repaire

#297 recruitments: applicants
  client/src/app/components/recruitment/recruitment-applicants/recruitment-applicants.component.html
  client/src/app/components/recruitment/recruitment-applicants/recruitment-applicants.component.ts
  client/src/app/services/recruitment.service.spec.ts
  client/src/app/services/recruitment.service.ts
  client/src/styles.scss
  src/main/java/com/hris/HRIS/controller/RecruiterController.java
  src/main/java/com/hris/HRIS/model/ApplyJobModel.java
Labels: wontfix
